### ISSUE TITLE
Duplicated scene in wroing seasons

### ISSUE THREAD

**Issue by hope-data-science** [EmilHvitfeldt/friends#4]
I find some data are wrong in the tibble `friends`, for instance:
```
library(friends)
library(tidyverse)
friends %>% filter(season==4,episode==21,scene==16) %>% select(text)%>% print(n = Inf)
```
This scene is in Season 1. I find duplicated entries in Season 1 too. Is there any way to check this data and make it right?

Thanks.

**Comment by EmilHvitfeldt** [comment]
Thank you for finding this error! 
You can install the updated version of the package using

```r
# install.packages("devtools")
devtools::install_github("EmilHvitfeldt/friends")
```

Please let me know if you find anything else!
